// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.0
// source: health.proto

package healthv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 健康状态
type Status int32

const (
	Status_STATUS_UNUSED Status = 0
	// 健康/就绪
	Status_STATUS_UP Status = 1
	// 不健康/未就绪
	Status_STATUS_DOWN Status = 2
	// 降级但可服务（可选）
	Status_STATUS_DEGRADED Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNUSED",
		1: "STATUS_UP",
		2: "STATUS_DOWN",
		3: "STATUS_DEGRADED",
	}
	Status_value = map[string]int32{
		"STATUS_UNUSED":   0,
		"STATUS_UP":       1,
		"STATUS_DOWN":     2,
		"STATUS_DEGRADED": 3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_health_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_health_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{0}
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{0}
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{1}
}

// 详细检查项
type Check struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 依赖名，如 "postgres", "redis", "kafka"
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// 单项状态
	Status Status `protobuf:"varint,2,opt,name=status,proto3,enum=gainetics.probe_executor.health.v1.Status" json:"status,omitempty"`
	// 错因或说明
	Reason string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	// 探测耗时
	LatencyMs int64 `protobuf:"varint,4,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	// 当前状态起始时间
	Since *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=since,proto3" json:"since,omitempty"`
	// 额外信息，如地址/库名等
	Metadata      map[string]string `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Check) Reset() {
	*x = Check{}
	mi := &file_health_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Check) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Check) ProtoMessage() {}

func (x *Check) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Check.ProtoReflect.Descriptor instead.
func (*Check) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{2}
}

func (x *Check) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Check) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNUSED
}

func (x *Check) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Check) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *Check) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

func (x *Check) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// 详细健康状态
type StatusReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 汇总状态（UP/DOWN/DEGRADED）
	Overall Status `protobuf:"varint,1,opt,name=overall,proto3,enum=gainetics.probe_executor.health.v1.Status" json:"overall,omitempty"`
	// 服务名
	Service string `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	// 版本信息
	VersionInfo *Version `protobuf:"bytes,3,opt,name=version_info,json=versionInfo,proto3" json:"version_info,omitempty"`
	// 进程已运行秒数
	UptimeSeconds int64 `protobuf:"varint,6,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	// 生成该响应的时间
	Now *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=now,proto3" json:"now,omitempty"`
	// 依赖项列表
	Checks        []*Check `protobuf:"bytes,8,rep,name=checks,proto3" json:"checks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusReply) Reset() {
	*x = StatusReply{}
	mi := &file_health_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusReply) ProtoMessage() {}

func (x *StatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusReply.ProtoReflect.Descriptor instead.
func (*StatusReply) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{3}
}

func (x *StatusReply) GetOverall() Status {
	if x != nil {
		return x.Overall
	}
	return Status_STATUS_UNUSED
}

func (x *StatusReply) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *StatusReply) GetVersionInfo() *Version {
	if x != nil {
		return x.VersionInfo
	}
	return nil
}

func (x *StatusReply) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *StatusReply) GetNow() *timestamppb.Timestamp {
	if x != nil {
		return x.Now
	}
	return nil
}

func (x *StatusReply) GetChecks() []*Check {
	if x != nil {
		return x.Checks
	}
	return nil
}

type Version struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	BuildTime     string                 `protobuf:"bytes,2,opt,name=build_time,json=buildTime,proto3" json:"build_time,omitempty"`
	BuildUser     string                 `protobuf:"bytes,3,opt,name=build_user,json=buildUser,proto3" json:"build_user,omitempty"`
	CommitId      string                 `protobuf:"bytes,4,opt,name=commit_id,json=commitId,proto3" json:"commit_id,omitempty"`
	GoVersion     string                 `protobuf:"bytes,5,opt,name=go_version,json=goVersion,proto3" json:"go_version,omitempty"`
	GoArch        string                 `protobuf:"bytes,6,opt,name=go_arch,json=goArch,proto3" json:"go_arch,omitempty"`
	BuildOs       string                 `protobuf:"bytes,7,opt,name=build_os,json=buildOs,proto3" json:"build_os,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Version) Reset() {
	*x = Version{}
	mi := &file_health_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Version) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Version) ProtoMessage() {}

func (x *Version) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Version.ProtoReflect.Descriptor instead.
func (*Version) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{4}
}

func (x *Version) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Version) GetBuildTime() string {
	if x != nil {
		return x.BuildTime
	}
	return ""
}

func (x *Version) GetBuildUser() string {
	if x != nil {
		return x.BuildUser
	}
	return ""
}

func (x *Version) GetCommitId() string {
	if x != nil {
		return x.CommitId
	}
	return ""
}

func (x *Version) GetGoVersion() string {
	if x != nil {
		return x.GoVersion
	}
	return ""
}

func (x *Version) GetGoArch() string {
	if x != nil {
		return x.GoArch
	}
	return ""
}

func (x *Version) GetBuildOs() string {
	if x != nil {
		return x.BuildOs
	}
	return ""
}

var File_health_proto protoreflect.FileDescriptor

const file_health_proto_rawDesc = "" +
	"\n" +
	"\fhealth.proto\x12\"gainetics.probe_executor.health.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\"\x14\n" +
	"\x12HealthCheckRequest\"\x0f\n" +
	"\rStatusRequest\"\xda\x02\n" +
	"\x05Check\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12B\n" +
	"\x06status\x18\x02 \x01(\x0e2*.gainetics.probe_executor.health.v1.StatusR\x06status\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x04 \x01(\x03R\tlatencyMs\x120\n" +
	"\x05since\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\x12S\n" +
	"\bmetadata\x18\x06 \x03(\v27.gainetics.probe_executor.health.v1.Check.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd5\x02\n" +
	"\vStatusReply\x12D\n" +
	"\aoverall\x18\x01 \x01(\x0e2*.gainetics.probe_executor.health.v1.StatusR\aoverall\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12N\n" +
	"\fversion_info\x18\x03 \x01(\v2+.gainetics.probe_executor.health.v1.VersionR\vversionInfo\x12%\n" +
	"\x0euptime_seconds\x18\x06 \x01(\x03R\ruptimeSeconds\x12,\n" +
	"\x03now\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x03now\x12A\n" +
	"\x06checks\x18\b \x03(\v2).gainetics.probe_executor.health.v1.CheckR\x06checks\"\xd1\x01\n" +
	"\aVersion\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"build_time\x18\x02 \x01(\tR\tbuildTime\x12\x1d\n" +
	"\n" +
	"build_user\x18\x03 \x01(\tR\tbuildUser\x12\x1b\n" +
	"\tcommit_id\x18\x04 \x01(\tR\bcommitId\x12\x1d\n" +
	"\n" +
	"go_version\x18\x05 \x01(\tR\tgoVersion\x12\x17\n" +
	"\ago_arch\x18\x06 \x01(\tR\x06goArch\x12\x19\n" +
	"\bbuild_os\x18\a \x01(\tR\abuildOs*P\n" +
	"\x06Status\x12\x11\n" +
	"\rSTATUS_UNUSED\x10\x00\x12\r\n" +
	"\tSTATUS_UP\x10\x01\x12\x0f\n" +
	"\vSTATUS_DOWN\x10\x02\x12\x13\n" +
	"\x0fSTATUS_DEGRADED\x10\x032\xa0\x03\n" +
	"\rHealthService\x12{\n" +
	"\bLiveness\x126.gainetics.probe_executor.health.v1.HealthCheckRequest\x1a\x16.google.protobuf.Empty\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/apis/health/v1/healthz\x12{\n" +
	"\tReadiness\x126.gainetics.probe_executor.health.v1.HealthCheckRequest\x1a\x16.google.protobuf.Empty\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/apis/health/v1/readyz\x12\x94\x01\n" +
	"\x06Status\x121.gainetics.probe_executor.health.v1.StatusRequest\x1a/.gainetics.probe_executor.health.v1.StatusReply\"&\x82\xd3\xe4\x93\x02 \x12\x1e/apis/health/v1/healthz/statusB5Z3github.com/jeffinity/app-layout/pkg/health;healthv1b\x06proto3"

var (
	file_health_proto_rawDescOnce sync.Once
	file_health_proto_rawDescData []byte
)

func file_health_proto_rawDescGZIP() []byte {
	file_health_proto_rawDescOnce.Do(func() {
		file_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_health_proto_rawDesc), len(file_health_proto_rawDesc)))
	})
	return file_health_proto_rawDescData
}

var file_health_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_health_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_health_proto_goTypes = []any{
	(Status)(0),                   // 0: gainetics.probe_executor.health.v1.Status
	(*HealthCheckRequest)(nil),    // 1: gainetics.probe_executor.health.v1.HealthCheckRequest
	(*StatusRequest)(nil),         // 2: gainetics.probe_executor.health.v1.StatusRequest
	(*Check)(nil),                 // 3: gainetics.probe_executor.health.v1.Check
	(*StatusReply)(nil),           // 4: gainetics.probe_executor.health.v1.StatusReply
	(*Version)(nil),               // 5: gainetics.probe_executor.health.v1.Version
	nil,                           // 6: gainetics.probe_executor.health.v1.Check.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 8: google.protobuf.Empty
}
var file_health_proto_depIdxs = []int32{
	0,  // 0: gainetics.probe_executor.health.v1.Check.status:type_name -> gainetics.probe_executor.health.v1.Status
	7,  // 1: gainetics.probe_executor.health.v1.Check.since:type_name -> google.protobuf.Timestamp
	6,  // 2: gainetics.probe_executor.health.v1.Check.metadata:type_name -> gainetics.probe_executor.health.v1.Check.MetadataEntry
	0,  // 3: gainetics.probe_executor.health.v1.StatusReply.overall:type_name -> gainetics.probe_executor.health.v1.Status
	5,  // 4: gainetics.probe_executor.health.v1.StatusReply.version_info:type_name -> gainetics.probe_executor.health.v1.Version
	7,  // 5: gainetics.probe_executor.health.v1.StatusReply.now:type_name -> google.protobuf.Timestamp
	3,  // 6: gainetics.probe_executor.health.v1.StatusReply.checks:type_name -> gainetics.probe_executor.health.v1.Check
	1,  // 7: gainetics.probe_executor.health.v1.HealthService.Liveness:input_type -> gainetics.probe_executor.health.v1.HealthCheckRequest
	1,  // 8: gainetics.probe_executor.health.v1.HealthService.Readiness:input_type -> gainetics.probe_executor.health.v1.HealthCheckRequest
	2,  // 9: gainetics.probe_executor.health.v1.HealthService.Status:input_type -> gainetics.probe_executor.health.v1.StatusRequest
	8,  // 10: gainetics.probe_executor.health.v1.HealthService.Liveness:output_type -> google.protobuf.Empty
	8,  // 11: gainetics.probe_executor.health.v1.HealthService.Readiness:output_type -> google.protobuf.Empty
	4,  // 12: gainetics.probe_executor.health.v1.HealthService.Status:output_type -> gainetics.probe_executor.health.v1.StatusReply
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_health_proto_init() }
func file_health_proto_init() {
	if File_health_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_health_proto_rawDesc), len(file_health_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_health_proto_goTypes,
		DependencyIndexes: file_health_proto_depIdxs,
		EnumInfos:         file_health_proto_enumTypes,
		MessageInfos:      file_health_proto_msgTypes,
	}.Build()
	File_health_proto = out.File
	file_health_proto_goTypes = nil
	file_health_proto_depIdxs = nil
}
