// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.31.0
// source: health.proto

package healthv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationHealthServiceLiveness = "/gainetics.probe_executor.health.v1.HealthService/Liveness"
const OperationHealthServiceReadiness = "/gainetics.probe_executor.health.v1.HealthService/Readiness"
const OperationHealthServiceStatus = "/gainetics.probe_executor.health.v1.HealthService/Status"

type HealthServiceHTTPServer interface {
	// Liveness Liveness（存活）：
	// - 健康时返回 gRPC OK（HTTP 200）
	// - 不健康时返回 gRPC Unavailable（HTTP 503）
	Liveness(context.Context, *HealthCheckRequest) (*emptypb.Empty, error)
	// Readiness Readiness（就绪：依赖可用、可接新流量）：
	// - 就绪时返回 gRPC OK（HTTP 200）
	// - 未就绪时返回 gRPC Unavailable（HTTP 503）
	Readiness(context.Context, *HealthCheckRequest) (*emptypb.Empty, error)
	// Status 详细状态（便于排障/观测）
	Status(context.Context, *StatusRequest) (*StatusReply, error)
}

func RegisterHealthServiceHTTPServer(s *http.Server, srv HealthServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/apis/health/v1/healthz", _HealthService_Liveness0_HTTP_Handler(srv))
	r.GET("/apis/health/v1/readyz", _HealthService_Readiness0_HTTP_Handler(srv))
	r.GET("/apis/health/v1/healthz/status", _HealthService_Status0_HTTP_Handler(srv))
}

func _HealthService_Liveness0_HTTP_Handler(srv HealthServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in HealthCheckRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHealthServiceLiveness)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Liveness(ctx, req.(*HealthCheckRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _HealthService_Readiness0_HTTP_Handler(srv HealthServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in HealthCheckRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHealthServiceReadiness)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Readiness(ctx, req.(*HealthCheckRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _HealthService_Status0_HTTP_Handler(srv HealthServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in StatusRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHealthServiceStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Status(ctx, req.(*StatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*StatusReply)
		return ctx.Result(200, reply)
	}
}

type HealthServiceHTTPClient interface {
	// Liveness Liveness（存活）：
	// - 健康时返回 gRPC OK（HTTP 200）
	// - 不健康时返回 gRPC Unavailable（HTTP 503）
	Liveness(ctx context.Context, req *HealthCheckRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// Readiness Readiness（就绪：依赖可用、可接新流量）：
	// - 就绪时返回 gRPC OK（HTTP 200）
	// - 未就绪时返回 gRPC Unavailable（HTTP 503）
	Readiness(ctx context.Context, req *HealthCheckRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// Status 详细状态（便于排障/观测）
	Status(ctx context.Context, req *StatusRequest, opts ...http.CallOption) (rsp *StatusReply, err error)
}

type HealthServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewHealthServiceHTTPClient(client *http.Client) HealthServiceHTTPClient {
	return &HealthServiceHTTPClientImpl{client}
}

// Liveness Liveness（存活）：
// - 健康时返回 gRPC OK（HTTP 200）
// - 不健康时返回 gRPC Unavailable（HTTP 503）
func (c *HealthServiceHTTPClientImpl) Liveness(ctx context.Context, in *HealthCheckRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/apis/health/v1/healthz"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHealthServiceLiveness))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Readiness Readiness（就绪：依赖可用、可接新流量）：
// - 就绪时返回 gRPC OK（HTTP 200）
// - 未就绪时返回 gRPC Unavailable（HTTP 503）
func (c *HealthServiceHTTPClientImpl) Readiness(ctx context.Context, in *HealthCheckRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/apis/health/v1/readyz"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHealthServiceReadiness))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Status 详细状态（便于排障/观测）
func (c *HealthServiceHTTPClientImpl) Status(ctx context.Context, in *StatusRequest, opts ...http.CallOption) (*StatusReply, error) {
	var out StatusReply
	pattern := "/apis/health/v1/healthz/status"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHealthServiceStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
